# Generated by Django 5.2.5 on 2025-10-20 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('nombre_temporal', models.CharField(max_length=255)),
                ('ruta', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('tamano', models.IntegerField()),
                ('descripcion_corta', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion_larga', models.TextField(blank=True, null=True)),
                ('descargas', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Archivo',
                'db_table': 'archivo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estatu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('createdat', models.DateTimeField(auto_now_add=True)),
                ('updatedat', models.DateTimeField(blank=True, null=True)),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('resumen', models.CharField(blank=True, max_length=255, null=True)),
                ('contenido', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('vistas', models.IntegerField(blank=True, null=True)),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.categoria')),
                ('fk_estatu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estatu')),
                ('fk_foto_portada', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.archivo')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicacion',
                'db_table': 'publicacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('created', models.DateTimeField()),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fk_estatu', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.estatu')),
                ('fk_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacion')),
            ],
            options={
                'verbose_name_plural': 'Comentario',
                'db_table': 'comentario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='PublicacionArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('fk_archivo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.archivo')),
                ('fk_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='core.publicacion')),
                ('fk_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Publicacion_archivo',
                'db_table': 'publicacion_archivo',
                'managed': True,
                'unique_together': {('fk_publicacion', 'fk_archivo')},
            },
        ),
    ]
